name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: '8.5'
      - name: Install dependencies
        working-directory: bridge
        run: composer install --no-interaction --prefer-dist
      - name: Run test suite
        working-directory: bridge
        run: ./vendor/bin/pest
